### PR TITLE
Cleanup, added gitignore

### PR DESCRIPTION
**Pull request by Danysan1**
Moved the signal types into daemonComm.h as constants (it's more clear now).
Added .gitignore file, useful for git.

### CODE REVIEW

**Comment by marazmista** [comment]
That's a lot of changes.

Let's investigate this part: 
``` c++  
dcomm->connectToDaemon();
        if (daemonConnected()) {
            //  Configure the daeomon to read the data
            dcomm->sendCommand(DAEMON_SIGNAL_CONFIG + '#' + filePaths.clocksPath);

            if(globalStuff::globalConfig.daemonAutoRefresh) //  If autoRefresh is enabled
                //  Tell the daemon to auto-refresh
                dcomm->sendCommand(DAEMON_SIGNAL_TIMER_ON + '#' + QString().setNum(globalStuff::globalConfig.interval));
        }
```
When I compile it with your branch of radeon-profile-daemon I got something like this:
```
Starting in debug mode
ok
connection
Received signal:  r_method/sys/kernel/debug/dri/0/radeon_pm_infomethod1
Unknown signal received
Opening file:  ""
QFSFileEngine::open: No file name specified
Unable to read file  ""
Writing into shared memory:  "null"
Written into shared memory:  null
Received signal:  2balanced#/sys/class/drm/card0/device/power_dpm_state#2low#/sys/class/drm/card0/device/power_dpm_force_performance_level#
Elaborating a SET_VALUE signal
Opening file:  ""
QFSFileEngine::open: No file name specified
Unable to read file  ""
Writing into shared memory:  "null"
Written into shared memory:  null
Received signal:  r/include/qt/QtCore/qlist.h/sys/class/drm/card0/device/hwmon/hwmon2/pwm1_enable
Unknown signal received
Opening file:  ""
QFSFileEngine::open: No file name specified
Unable to read file  ""
Writing into shared memory:  "null"
Written into shared memory:  null
disconnect
```
There is something wrong in line 4:
Received signal:  **r_method**/sys/kernel/debug/dri/0/radeon_pm_info**method1**
No data because daemon has wrong path on his side.
Now, let's modify it to:
```c++

        dcomm->connectToDaemon();
        if (daemonConnected()) {
            //  Configure the daeomon to read the data
            QString signalConfig = "0";
            dcomm->sendCommand(signalConfig + '#' + filePaths.clocksPath);

            if(globalStuff::globalConfig.daemonAutoRefresh) //  If autoRefresh is enabled
                //  Tell the daemon to auto-refresh
                dcomm->sendCommand(DAEMON_SIGNAL_TIMER_ON + '#' + QString().setNum(globalStuff::globalConfig.interval));
        }
```
Output:
```
Starting in debug mode
ok
connection
Received signal:  0#/sys/kernel/debug/dri/0/radeon_pm_infomethod1
Elaborating a CONFIG signal
Copying  "/sys/kernel/debug/dri/0/radeon_pm_infomethod1"
Opening file:  "/sys/kernel/debug/dri/0/radeon_pm_infomethod1"
Unable to read file  "/sys/kernel/debug/dri/0/radeon_pm_infomethod1"
Writing into shared memory:  "null"
Written into shared memory:  null
```
Begining looks good, but something at the end:
Received signal:  0#/sys/kernel/debug/dri/0/radeon_pm_info**method1**
From where the `method1` came from? I don't know but let's modify:
```c++
        dcomm->connectToDaemon();
        if (daemonConnected()) {
            //  Configure the daeomon to read the data
            QString signalConfig = "0";
            dcomm->sendCommand(signalConfig + '#' + filePaths.clocksPath);

            if(globalStuff::globalConfig.daemonAutoRefresh) {//  If autoRefresh is enabled
                QString test = "TEST";
                //  Tell the daemon to auto-refresh
                dcomm->sendCommand(test + '#' + QString().setNum(globalStuff::globalConfig.interval));
            }
        }
```
Output:
```
Starting in debug mode
ok
connection
Received signal:  0#/sys/kernel/debug/dri/0/radeon_pm_infoTEST#1
Elaborating a CONFIG signal
Copying  "/sys/kernel/debug/dri/0/radeon_pm_infoTEST"
Elaborating a READ_CLOCKS signal
Opening file:  "/sys/kernel/debug/dri/0/radeon_pm_infoTEST"
Unable to read file  "/sys/kernel/debug/dri/0/radeon_pm_infoTEST"
Writing into shared memory:  "null"
Written into shared memory:  null
```
As you can see, those two signals get mixed somehow and hence the scary line in original code:

```c++
dcomm->sendCommand(dcomm->daemonSignal.config +"#" + filePaths.clocksPath + "#"+ ((globalStuff::globalConfig.daemonAutoRefresh) ? dcomm->daemonSignal.timer_on + "#" + QString().setNum(globalStuff::globalConfig.interval) : ""));
```
(Side note: When I tried all this above, I found reason of bug in daemon. In this line signal for timer to turn on goes with interval divided by `"#"`, but later in `dXorg::reconfigureDaemon()` method it is send without `"#"`. My oversight.)

Interestingly enough, those #define declarations work fine with other signals, but for consistency I wrote all of them in struct with signals, so I don't think changing it is a good change (actually, changing them to `const QString` may be better idea). Do they work OK for you? Do you get those distorted config signals? Also, I don't know why you've replaced all of `"#"` to `'#'`. After all, everything is converted to QString. Also if you hover in QtCreator over first one you get the type `const char*`(looks like string though), while latter is `char`.

I like the simplification of `dXorg::setPwmManuaControl(bool manual)` but it doesn't work in its current form:
```c++
void dXorg::setPwmManuaControl(bool manual) {
    char mode = manual ? pwm_manual : pwm_auto;

    if (daemonConnected()) {
        //  Tell the daemon to set the pwm mode into the right file
        dcomm->sendCommand(DAEMON_SIGNAL_SET_VALUE + mode + '#' + filePaths.pwmEnablePath);
    } else  //  No daemon available
        setNewValue(filePaths.pwmEnablePath, "" + mode);
}
```
You omitted the `"#"` at the end of signal. Also this `"" + mode` is very weird type conversion IMO (very JavaScript like). Better use `(QString)mode`.
I would rewrite it to (which questions a little changes to chars of all `pwm_*` #defines in `globalStuff.h`):
```c++
void dXorg::setPwmManuaControl(bool manual) {
    QString mode = manual ? pwm_manual : pwm_auto;

    if (daemonConnected()) 
        //  Tell the daemon to set the pwm mode into the right file
        dcomm->sendCommand(daemonComm::daemonSignal.setValue + mode + "#" + filePaths.pwmEnablePath+ "#");
     else  //  No daemon available
        setNewValue(filePaths.pwmEnablePath, mode);
}
```

What do you think about all this? Thanks for your contribution and support :)

**Comment by Danysan1** [comment]
Debugging again i noticed those problems too. Looks like + and << operators go in confusion with types different from QString and string. Looks also like QLocalSocket tries to optimize communication by joining commands. 
The solution to the first problem was utilizing directly QString::append(), which is much more predictable.
The solution to the second problem can only be partially solved here, the main problem is on the daemon. On this side I put a SEPARATOR ('#') at the end of each instruction, which allows to distinguish them; but that doesn't change the fact that occasionally the GUI can spit out into the daemon commands like 
```
2balanced#/sys/class/drm/card0/device/power_dpm_state#2auto#/sys/class/drm/card0/device/power_dpm_force_performance_level#
```
or
```
0#/sys/kernel/debug/dri/0/radeon_pm_info#1#
```
which are theoretically vaild, but as of today cannot be read by the daemon (actually it reads the first part, but it ignores the latter). The next work to be done is rework the communication reception system of the daemon.
The first idea that comes in my mind is adding a simple QQueue<QString> into rpdthread::performTask(), when a message arrives it is split in to QStrings and each QString is added to the QQueue, then the function cycles over the QQueue dequeing it until it's empty, however this discussion should be done in an issue in radeon-profile-thread...

**Comment by Danysan1** [comment]
Also, i fixed the `"" + mode` (which I admit was really ugly).

Finally, I added here the same function of radeon-profile-daemon that removes all the qDebug() lines if it is not compiled for debug

**Comment by marazmista** [comment]
There is an error in dxorg.cpp, line 62 (`reconfigureDaemon()` method):
```c++  
 command.append(QString::number(globalStuff::globalConfig.interval)).append(SEPARATOR); // Set timer interval
```
daemon:
```
Elaborating a TIMER_ON signal
Invalid value TIMER_ON value:  "1#"
```
Happens when you uncheck autorefresh, then reconfigure and then check again and reconfigure. Leftover separator at the end, causes `toInt()` fail on daemon side.

Also, you don't need QString() after equation mark when you decided against pointers:
```c++
QString command = QString();
```
to:
```c++
QString command;
```

**Comment by Danysan1** [comment]
Fixed the TIMER_ON parsing in https://github.com/Danysan1/radeon-profile-daemon/commit/71118adbdff6461bd4dae6723fa3ca6837e91ba7 and cleaned up the '= QString()' declarations in https://github.com/Danysan1/radeon-profile/commit/467a940be50ce31b706fcb52043651c80f931078

**Pull request merged**
