### PR TITLE
configure, make install, AppStream, Flatpak, ioctl

### PR DESCRIPTION
**Pull request by Danysan1**
To install all files into $exampleDir run:
./configure --prefix=$exampleDir
make
make install

### CODE REVIEW

**Comment by Danysan1** [comment]
For some reason 'make install' still does not install translation files. I am trying to understand why.

**Comment by Danysan1** [comment]
Summing up the changes of this pull:
- radeon-profile/radeon-profile.pro
Implemented the automated installation through the Makefile `install` target. After running `qmake` and `make`, running `make install` will automatically install all the files (see below for the exact directories).
- radeon-profile/configure
This script automatically collects CXXFLAGS, installation prefix and other info and calls qmake (whether it is from Qt5 or Qt4).

In combination with the first point, this completes the standard linux 3-step build process; running inside the radeon-profile directory the command sequence:
```
./configure --prefix=...
make
make install DESTDIR=...  INSTALL_ROOT=...
```
will install these files:
```
$INSTALL_ROOT/$DESTDIR/$PREFIX/bin/radeon-profile
$INSTALL_ROOT/$DESTDIR/$PREFIX/share/icons/hicolor/512x512/apps/radeon-profile.png
$INSTALL_ROOT/$DESTDIR/$PREFIX/share/applications/radeon-profile.desktop
$INSTALL_ROOT/$DESTDIR/$PREFIX/share/appdata/radeon-profile.appdata.xml
$INSTALL_ROOT/$DESTDIR/$PREFIX/share/radeon-profile/strings.*.qm
```
I moved the icon from `/share/pixmaps/` to `/share/icons/hicolor/512x512/apps/` because that's the path structure where [the Freedesktop standard](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#install_icons) suggests to put the icons.
This also allows to simplify the packaging scripts, automating the install process (for example, [old PKGBUILD](https://build.opensuse.org/package/view_file/home:danysan95/radeon-profile/PKGBUILD?expand=1)->[new PKGBUILD](https://build.opensuse.org/package/view_file/home:danysan95/radeon-profile-test/PKGBUILD?expand=1), [old debian.rules](https://build.opensuse.org/package/view_file/home:danysan95/radeon-profile/debian.rules?expand=1)->[new debian.rules](https://build.opensuse.org/package/view_file/home:danysan95/radeon-profile-test/debian.rules?expand=1), [old .spec](https://build.opensuse.org/package/view_file/home:danysan95/radeon-profile/radeon-profile.spec?expand=1)->[new .spec](https://build.opensuse.org/package/view_file/home:danysan95/radeon-profile-test/radeon-profile.spec?expand=1))

- radeon-profile/extra/radeon-profile.appdata.xml
This file contains meta-data info for [the Appstream standard](https://www.freedesktop.org/wiki/Distributions/AppStream/), used by app stores like Gnome Software.

- radeon-profile/extra/radeon-profile.desktop
Minor improvements.

- flatpak-builder.json
Manifest file for [flatpak-builder](http://flatpak.org/developer.html#Building_More_Complex_Apps_With_flatpak_builder), which automatically builds (configure,make,make install) a Flatpak package (an architecture independent portable application package). Running inside the main directory this command:
`flatpak-builder --repo=repo temp flatpak-builder.json`
will create a repository into repo/, build radeon-profile into temp/ and package it into the repository ([the KDE Sdk (org.kde.Sdk)](https://community.kde.org/Guidelines_and_HOWTOs/Flatpak#KDE_Runtime) is necessary to build it, for Qt). To install it ([the KDE Runtime (org.kde.Platform)](https://community.kde.org/Guidelines_and_HOWTOs/Flatpak#KDE_Runtime) is necessary, for Qt):
`flatpak --user remote-add --no-gpg-verify rp repo`
To run it:
`flatpak --user install rp org.rp.RadeonProfile`

- radeon-profile/globalStuff.h   radeon-profile/dxorg.cpp   radeon-profile/uiEvents.cpp 
Fix PROFILE radeon power method, which was not detected with the daemon ([diff](https://github.com/marazmista/radeon-profile/pull/43/files#diff-b8580399f50e58d4af61da6275e60c61R631)) and did not work correctly with combo_pProfile on HIGH and LOW profiles ([diff](https://github.com/marazmista/radeon-profile/pull/43/files#diff-89e5e8abdfb63eeaffe857bb30980e1eL75)). Also, small cleanups ([diff](https://github.com/marazmista/radeon-profile/pull/43/files#diff-b8580399f50e58d4af61da6275e60c61R472), [diff](https://github.com/marazmista/radeon-profile/pull/43/files#diff-b8580399f50e58d4af61da6275e60c61R504), [diff](https://github.com/marazmista/radeon-profile/pull/43/files#diff-ca703f8a6e789cfb24a4f1681dacba93L331)).

- radeon-profile/gpu.cpp 
Fix FGLRX initialization, which did not check the list of GPUs ([diff](https://github.com/marazmista/radeon-profile/pull/43/files#diff-03bfb2003c63e5bca9b3e10acc461aaf))

- radeon-profile/main.cpp
Added a splash screen that indicates the app loading while radeon-profile loads and waits for radeon-profile-daemon, which can seem a long time.

- radeon-profile/radeon_profile.cpp  radeon-profile/radeon_profile.h
Fix Qt4 build.

- radeon-profile/translations/strings.it.ts
Update Italian translation

**Comment by marazmista** [comment]
Instead of changing title and push into one pull request as much changes as you can, please do small pull request for each feature when you consider it complete and tested because, when you make a pull request and then still keep committing changes after which code looks nothing like it was when pull request was opened, it is impossible to review.

**Comment by Danysan1** [comment]
Ok, I have solved merge conflicts and split this pull in four parts:
1) IOCTLs: [Patch](https://gist.github.com/Danysan1/bcb6fad12ad73f8e6d73ac58aeb3593f#file-ioctl-patch),     [Branch](https://github.com/Danysan1/radeon-profile/tree/add_ioctl),     [Pull request](https://github.com/marazmista/radeon-profile/pull/44)
2) Configure, make install, flatpak: [Patch](https://gist.github.com/Danysan1/bcb6fad12ad73f8e6d73ac58aeb3593f#file-configure-patch),     [Branch](https://github.com/Danysan1/radeon-profile/tree/add_configure),     [Pull request](https://github.com/marazmista/radeon-profile/pull/45)
3) Fixes to PROFILE power method: [Patch](https://gist.github.com/Danysan1/bcb6fad12ad73f8e6d73ac58aeb3593f#file-profile_fixes-patch),     [Branch](https://github.com/Danysan1/radeon-profile/tree/add_profile_fixes)
4) Fixes for FGLRX driver, improved first data read and splash screen:  [Patch](https://gist.github.com/Danysan1/bcb6fad12ad73f8e6d73ac58aeb3593f#file-fixes-patch),     [Branch](https://github.com/Danysan1/radeon-profile/tree/add_fixes)

**Comment by Danysan1** [comment]
Leaving the four separate branches to merge, closing.

**Pull request closed without merging**
