### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Danysan1**
- The first commit cleans up a lot of code using daemon communication or globalStuff structures.
- The second commit fixes some UI elements and adds two options (one allows to choose if combo_pProfile and combo_pLevel should be shown and the other allows to show combo_gpus only if multiple cards are present).
- The third commit inserts into the gpuClocksStruct some validity check flags that allow to reduce the number of operations and lines of code.

### CODE REVIEW

**Comment by marazmista** [comment]
Why do you modified those enums in globalStuff to typedefs? This is unnecessary change that has no benefit. Seems like a change for the sake of change.
Why do you modified logs format? Now, there is no simple way to paste log to Calc or something to make graph, because labels are in every line instead of just values separated with ;
Why do you removed parameters from function that converts values to string? It was const reference after all and explicitly you could tell what is being converted instead some global struct now.
You've modified code for reading clocks from old Profile file format in debugfs (thing before DPM). Did you test it? Will it segfault when there is no one or another value available in file?
Fonts at the top part of the window are broken again, and there is a lot of wasted space(screen below). Checkboxes for choosing which graph should be displayed, aren't working correctly now (screen below). Graphs card is not disabled when I disable graphs in configuration. Stats tab is not disabled when I disable it config. Overclock tab should be disabled when there is no overclock (just like fan tab).
Also, in exec tab when I want to add variable to command and I click Ok, it ask me whether remove old or not even if  there is no such value in summary. This was modified in previous pull, and worked fine before. (Looked like this before: https://github.com/marazmista/radeon-profile/blob/7febbac63be268d1dba233997243a1f76d528344/radeon-profile/execTab.cpp#L145)
You seem to modify a lot of code at once, but are you actually test it? It's obvious that bugs will be here or there but I don't see the point in rewriting same things, that are working right, over and over again without introducing something new or visibly improving code.
2016-05-27-192258_3840x1080_scrot

**Comment by Danysan1** [comment]
globalStuff typedefs: because putting those enums and structs in a class when they are used everywhere as a type clutters the code with lots of useless references to globalStuff.

log format: because all the entries were in offset from their label, making them really hard to read. I will revert this, but the old format is not perfect.

gpu::convertClocks and gpu::convertTemperature: because on each update the function wasted time creating and passing a new struct when in fact the struct will always replace the same already existent struct, wasting time.

profile file reading: i guess you are talking about dxorg.cpp lines 214-236. Ok i just noticed it should be (2 < count), (4 < count) and (5 < count).

fonts broken: They look fine in your screenshot (monospace, 10pt, like before), how are they broken?

space wasted: Those are the default spacing of TableLayout, I will adjust them.

graphs broken: Ok, I found the problem and will solve it.

graphsTab, overclockTab and statsTab: those tabs are disabled, if you select one of those tabs you'll see that it's all greyed out (disabled). OverclockTab also shows the reason why it's disabled ("no root or daemon" or "not supported").

"remove" dialog in execTab: this bug was present even before my previous pull (try running https://github.com/marazmista/radeon-profile/tree/7930f208d8057a1302bd0a48ad5aaa4995afbb1b , which is the last state of the repo before the incriminated commit: it asks to remove the value even if it is not present, like now. The new condition ((varIndex != -1) || ok) behaves in the same way of the precedent (varIndex != -1 && !ok || ok) ). Also, from the comment to the line of code it's not clear what's the objective: if you want to show the dialog when the value is already present wether the user clicked Ok or Cancel it is sufficient (varIndex != -1); if you want to show it only if the values is already present and the user clicked Ok the correct condition is ((varIndex != -1) && ok).




Yes, I test the code I write even if this time I lost the bug in the profile file reading and the broken graphs.

**Comment by Danysan1** [comment]
I've added some new functions:
* Support for integrated Intel graphic cards (kernel module i915). Shows clock, temperature, glx info, connectors, module parameters and history of power levels. It works out of the box (does not require root access). Here are some screenshots:
screenshot_20160619_171459
screenshot_20160618_162009
 Before adding the Intel module, in order to [make expanding more easy](https://en.wikipedia.org/wiki/Open/closed_principle), I changed the structure of the 'gpu' class: now each driver module (dXorg, dFglrx, dIntel) is a class that extends 'gpu' implementing/extending the available functions and updating the 'features' struct to say what functions are available. Now all it is needed to add a driver module is implement the functions and edit radeon_profile::detectDriver(), without the need to edit any function in gpu.cpp (before you had to edit each function in gpu.cpp). Here is the UML diagram:
diagram
So, the available drivers are:
  * Xorg (radeon) (tested)
  * Xorg (amdgpu) (not tested, same code of your rp-amdgpu branch)
  * Intel (i915) (tested)
  * Catalyst (fglrx) (not tested, mostly the same code as before of this pull request)

* In the GLX info box I improved the OpenGL info and added support for Vulkan info (from vulkaninfo) and OpenCL info (from clinfo). Some screenshots:
screenshot_20160619_185400
screenshot_20160619_185437
screenshot_20160619_171254

* In the graph tab I added the option to export the graphs in PDF/PNG/JPG/BMP. Here is an example:
screenshot_20160619_194143
screenshot_20160619_194148
This is the output file temperature.png:
temperature
frequency.png:
frequency
volts.png:
volts

* I fixed the tray icon on Unity where it was problematic: on ubuntu <= 14, where it was not visible, I introduced a variable that prevents the application to be minimized to tray; on ubuntu > 14, where the window could not be restored from tray, i added to the tray menu a button to show the window.

* I fixed the data detection with the "profile" power method in dXorg, where the shared memory was too small and truncated the data and the order of combo_pProfile was wrong; increasing the shared memory size requires a change also on the daemon.
screenshot_20160619_205200

* I added a check that controls and warns the user if any executable is running when the application is being closed.

* Improved setupUiEnabledFeatures()

* Fixed the graphs tab when no graph is visible:
screenshot_20160619_204055

**Comment by muzena** [comment]
@Danysan1 
Can you tell me how to add localization, I made strings.hr.ts from strings.it.ts file and translate string, add TRANSLATIONS += strings.hr.ts DISTFILES += strings.hr.ts in radeon-profile.pro file then I generate debs but it dosen't work.
Then I generate strings.hr.qm and try like it's says in instructions in radeon-profile.pro file, but nothing work.

**Comment by Danysan1** [comment]
Strange.. What's the output of `lrelease`? My output is:
`Updating '/home/daniele/radeon-profile/radeon-profile/strings.it.qm'...`
`Generated 240 translation(s) (240 finished and 0 unfinished)`
You should see another line for strings.hr.ts, is it present?
Did you put the .qm file into the right folder?

**Comment by muzena** [comment]
@Danysan1 
I don't understand lrelease and lupdate how to run this, Can you describe. I have generate *.qm file with Qt 4 Linguist, when I try run from terminal lrelease and lupdate, this two commands is listing help.

**Comment by Danysan1** [comment]
lrelease and lupdate from command line require the .pro file as argument. Anyway, if the .qm file is generated lrelease is probably working properly.

Did you copy the strings.hr.qm file into the folder where the executable is ( or in /usr/share/radeon-profile/ ) ?

**Comment by muzena** [comment]
YesI have radeon-profile and radeon-profile-daemon in /usr/bin there I copy strings.hr.qm.
But dosen't work

**Comment by Danysan1** [comment]
Try after this commit

**Comment by Danysan1** [comment]
BTW /usr/bin is a folder dedicated to binaries, you shouldn't put translations in it

**Comment by muzena** [comment]
@Danysan1 
Yes I know that /usr/bin is for binaries, why don't you make to put translations qm files in to /usr/share/locale folder?

**Comment by muzena** [comment]
Works from i move radeon-profile an strings,hr-qm to /usr/share/radeon-profile and now works translation in /usr/bin dosen't work.

**Comment by Danysan1** [comment]
/usr/share/locale/ requires all files to be in separate folder (one for each language) and all translations should be renamed radeon_profile.<language>.{ts|qm} because the folders are shared with other packages. For me it's ok but you'll need also to change your translation file name

**Comment by muzena** [comment]
@Danysan1 
I found a few poblems.
See in this screenshots below:
Marked with red lines: It's shows some strange character
Marked with blue lines systray icon: It's wrong it shoud be Balanced 
Marked with green lines: It's not shown all translated string, string line/row is to short.
slika1
slika2
slika3

**Comment by Danysan1** [comment]
The red line problem and green line problem should now be ok.
The blue line problem was already fixed in the development branch: https://github.com/Danysan1/radeon-profile/commit/3256e6538795ac6c5673504d298c0f8504a960a9#diff-4f2e218a1642bfe5fe70ec507099744eR114

**Comment by muzena** [comment]
@Danysan1 
How do I now update strings.hr.ts file?

**Comment by Danysan1** [comment]
once you pulled from git the commits go in radeon-profile/ (the folder with the .ts and the .pro files) and run `lupdate radeon-profile.pro`

**Comment by muzena** [comment]
@Danysan1 
I second screenshot marked with red that strange character is still present.

**Comment by Danysan1** [comment]
using the development branch? That's really strange, since i removed it..
Can you post your strings file in https://gist.github.com/ ?

**Comment by muzena** [comment]
@Danysan1 
Yes today I compile Development branch and install.
What string?
I don't use cyrilic, I use latin letters.

**Comment by Danysan1** [comment]
I meant the strings file (strings.hr.ts), so i can test what's not working.

**Comment by muzena** [comment]
@Danysan1 
Is this ok?
https://gist.github.com/muzena/83c47deacb92672770a8717c537565c2

**Comment by Danysan1** [comment]
On my computer it works fine:
screenshot_20160629_122559

**Comment by Danysan1** [comment]
[but the translation is not updated]

**Comment by muzena** [comment]
I updatedt it with command:
lupdate radeon-profile.pro
Updating 'strings.hr.ts'...
    Found 228 source text(s) (0 new and 228 already existing)
Updating 'strings.it.ts'...
    Found 228 source text(s) (0 new and 228 already existing)

**Comment by marazmista** [comment]
1. Fonts at the top, master:

Development:


2. Closing app (or tab) while there is something running that was started from Exec tab should not terminate that process.
3. Don't set _tData.coreClkOk_ (and alike) in every data read (_getClocks()_). There is a reason why _figureOutDriverFeatures()_ was created and _features.coreClockAvailable_ tells that something is available or not. We won't suddenly get, for example, read about memory clock while program is running. When something is bigger that 0, it gets displayed (UVD clocks for instance, 0 when decoder not used but available in overall). Those _*Ok_ variables are therefore redundant, everything can be accomplished using _*Available_ variables.

**Pull request closed without merging**
