### PR TITLE
Check validity of clocks and voltages, fix radeon_profile::refreshUI()

### PR DESCRIPTION
**Pull request by Danysan1**
* Show clocks and voltages only if the values are valid ( > 0 )
* Fix voltages show control in radeon_profile::refreshUI()
* Improve string creation in radeon_profile::doTheStats()

### CODE REVIEW

**Comment by marazmista** [comment]
0 is valid value.

**Comment by Danysan1** [comment]
Look at this screenshot from my PC (this branch on the left, master on the right):

schermata da 2016-12-20 22-30-28

A vddci of 0 would mean that the memory and I/O is powered off, which is clearly false since it has a frequency of 600 MHz (also, it would be impossible).
Here's the content of /sys/kernel/debug/dri/0/radeon_pm_info:

>uvd    vclk: 0 dclk: 0
>power level 0    sclk: 20000 mclk: 60000 vddc: 900 vddci: 0

So all values to 0 are either not valid/available or powered off, so not influential

**Comment by marazmista** [comment]
If you're talking about this fix https://github.com/marazmista/radeon-profile/pull/41/commits/ed9a2ded1fb69ba0df86cd576136cac772f8522f#diff-cda7bc0581cc82ab9f765694a7a02bc6R275 then fine, but there is no reason not to leave != -1 everywhere as it is.

**Comment by marazmista** [comment]
Can you make the pull with just coreVolt/memVolt switched in lines mentioned above and Qt4 build fix? https://github.com/marazmista/radeon-profile/pull/41/commits/7c83437b6be9d34a305ecc94ca78a0537d0ea8df

**Comment by Danysan1** [comment]
You want to revert also the changes in doTheStats()? why?

**Comment by marazmista** [comment]
Beacuse it works ok, and it's less code.

**Comment by Danysan1** [comment]
It's much more clear this way

**Comment by marazmista** [comment]
Depends. Besides it is not something used by many other things and something that is heavily modified every other commit.

**Pull request merged**
