### PR TITLE
Moving getCardConnectors() from Xrandr to libXRandr

### PR DESCRIPTION
**Pull request by Danysan1**
This branch is actually not ready for merge (a lot of things are still missing), but I'm working on moving the getCardConnectors function in dxorg.cpp (which supplies the connectors tab in the GUI) from parsing XRandr to naively interface with the C library on which XRandr itself is implemented, called libXRandr.
This allows to show much more information, and to be more flexible. I still haven't deleted the old implementation to show the difference (though now it compiles only in debug mode), take a look (this was compiled in debug mode, so the top five lines are the output of the old implementation):

[Debug mode, single monitor active](https://cloud.githubusercontent.com/assets/8406735/12537898/c8065c64-c2cb-11e5-82f6-7c5e5dc76500.png)

[Debug mode, two monitors active](https://cloud.githubusercontent.com/assets/8406735/12537906/e9a8b57e-c2cb-11e5-8374-ec28d5ec7616.png)

Here is in release mode:

[Release mode, single monitor active](https://cloud.githubusercontent.com/assets/8406735/12537920/1f217416-c2cc-11e5-8325-ac9ff8be58a3.png)

[Release mode, two monitors active](https://cloud.githubusercontent.com/assets/8406735/12537922/2fd8fc5c-c2cc-11e5-8ddb-5ff819181818.png)

Here is in release mode with the monitor properties expanded

[Release mode, single monitor active, properties expanded](https://cloud.githubusercontent.com/assets/8406735/12537925/5c62f4bc-c2cc-11e5-9db9-ceadd8433117.png)

The actual missing features are refresh rates and possible alternative resolutions for the outputs, I'm working on them.
For much more details you can take a look at the code comments (i wrote a lot of details there) and at the first commit message.

I also did a minor edit to radeon_profile.cpp, now the GUI scales its dimension on the screen resolution.

### CODE REVIEW

**Comment by Danysan1** [comment]
Wow git has done some chaos doing the rebase of the branch on your master (https://github.com/marazmista/radeon-profile/network is more clear), anyway in this commit I added the refresh rate recognition and the list of available resolution for the monitor, plus some minor improvements like precising if the monitor name is unknown. Here's how it looks now:

[Release mode, single monitor active](https://cloud.githubusercontent.com/assets/8406735/12552076/a90465b4-c36f-11e5-8826-e5a5171152e3.png)

[Release mode, two monitors active](https://cloud.githubusercontent.com/assets/8406735/12552087/c5270558-c36f-11e5-85cd-d51be01f5d34.png)

A couple of details are still missing, like the translation of certain properties to correct values.

**Comment by Danysan1** [comment]
The new connectors panel is complete, here are some screenshots:

[Debug mode, multiple screen](https://cloud.githubusercontent.com/assets/8406735/12702333/893fc2d0-c826-11e5-9ea8-2db0adad9498.png)

[Debug mode, single screen active](https://cloud.githubusercontent.com/assets/8406735/12702336/94681734-c826-11e5-972b-6759bc77b789.png)

[Release mode](https://cloud.githubusercontent.com/assets/8406735/12702337/97610a2c-c826-11e5-9074-190bce978936.png)

[Available modes expanded](https://cloud.githubusercontent.com/assets/8406735/12702338/9a4cf778-c826-11e5-8b58-f774158a3b8f.png)

[Properties expanded](https://cloud.githubusercontent.com/assets/8406735/12702339/9ce08f36-c826-11e5-9e7b-ecf4d080f6ba.png)

**Comment by marazmista** [comment]
Looking good. What do you think about moving it to gpu.cpp, since this is rather driver independent feature?

**Comment by Danysan1** [comment]
Okay, done.

**Comment by Danysan1** [comment]
I just pushed a commit where I added an internationalization system through Qt translation framework. Right now the only language available (other than english) is italian.
I also edited the UI, improving the top area look, this is the new look:
screenshot_20160424_150212


Here is a screenshot comparing old (left) and new (right):
screenshot_20160424_145334

**Comment by Danysan1** [comment]
@marazmista what do you think about it?

**Comment by marazmista** [comment]
Sorry for delayed reply.

Good in overall. But I don't see any reason to change labels on top of window. Labels will always have problems with alignment and length of text. 
rp
I intentionally did this with readonly textboxes with monospace font, because you have fixed box with text inside which will never go out of it and everything was fine. The looks of it is theme dependent. I know it was lot to change, but I would suggest revert. Also, why setting up 2/3 of the screen at start? There is an option to save window size, so user can check it and have a desired size on launch. Indention of lower combobox was planned too, for some kind of hierarchy. Rest seems to be ok :)
I will merge next week, because I will be away till then.

**Comment by Danysan1** [comment]
For the 2/3 size: the window will expand to 2/3 only if no geometry is saved: if the user has checked the Save Window Geometry setting, the window will resize to the saved geometry.

For the label change: I changed it because QLineEdit forms were ugly looking (the background does not conform to the surrounding area [and it can only be changed by setting it in the style sheet with a fixed colour](http://stackoverflow.com/a/21330611/2347196) and that would not work with all themes). I tried to avoid text length problems by using the Noto Mono but looks like it's not enough. Can you check if the problem persists after setting label the font to Monospace? Otherwise i can revert the change.

Thank you.

**Comment by marazmista** [comment]
Don't you think 2/3 is too big? And maybe this part belongs to settings.cpp? There is already code, that read the window geometry
```c++
    // apply some settings to ui on start //
    if (ui->cb_saveWindowGeometry->isChecked())
        this->setGeometry(settings.value("windowGeometry").toRect());
```
so as you've said, when there is no size saved it may set fixed size.

Monospace seems to solved this issue. Also temperature label needs to hold values like 50,5*C (there was a report about values with comma).

**Comment by Danysan1** [comment]
Perfect, tomorrow I'll change the label font to monospace, resize the temperature label and move the size code to settings.cpp. 
Regarding the 2/3 ratio: IMHO it is ok but I can change it, 1/2 is ok?

**Comment by marazmista** [comment]
Sure, no problem.

**Pull request merged**
